#### `logical reg`

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
from sklearn.datasets import make_classification

In [51]:
x,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [52]:
df = pd.DataFrame(x,columns=np.arange(10))

In [53]:
df

0         1         2  ...         7         8         9
0    0.964799 -0.066449  0.986768  ... -1.210161 -0.628077  1.227274
1   -0.916511 -0.566395 -1.008614  ... -0.984534  0.363896  0.209470
2   -0.109484 -0.432774 -0.457649  ... -0.246383 -1.058145 -0.297376
3    1.750412  2.023606  1.688159  ... -0.357445 -1.473127 -0.190039
4   -0.224726 -0.711303 -0.220778  ... -0.939156  0.175915  0.236224
..        ...       ...       ...  ...       ...       ...       ...
995 -1.367638  1.462255 -1.154918  ...  1.428760  1.687092  1.072542
996 -1.514876 -3.221016 -1.300744  ... -1.680870  1.798510  0.034272
997  1.674633  1.754933  1.586154  ...  0.692723 -1.503850  0.225264
998 -0.778609 -0.835689 -0.194842  ... -0.497354  2.472138  0.867187
999  0.248454 -1.003439  0.360460  ...  0.773240  0.185734  1.416412

[1000 rows x 10 columns]

In [54]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [55]:
from sklearn.linear_model import LogisticRegression
logic_reg = LogisticRegression()


In [56]:
logic_reg.fit(x_train,y_train)

LogisticRegression()

In [57]:
y_pred = logic_reg.predict(x_test)

In [58]:
logic_reg.predict_proba(x_test)[:,0]

array([7.74477909e-01, 3.36684957e-02, 6.70682154e-01, 7.98668032e-02,
       9.76616650e-01, 4.13572804e-02, 9.79028767e-01, 9.59367261e-01,
       8.08520049e-01, 6.84954318e-01, 9.13669448e-01, 2.63597018e-01,
       5.25844192e-01, 2.11912354e-01, 7.93592056e-01, 9.46621678e-01,
       2.62957933e-02, 3.24212617e-01, 3.14803584e-01, 2.04956217e-01,
       5.04587065e-01, 9.66703630e-01, 2.00514796e-01, 7.77891908e-01,
       8.72986315e-01, 4.01990726e-02, 9.21218522e-01, 8.14302359e-01,
       4.84323961e-01, 3.45979014e-01, 6.82517287e-02, 5.40154632e-04,
       9.69329756e-01, 9.72909425e-01, 9.42369499e-01, 5.19300818e-01,
       8.46478994e-02, 3.25968944e-01, 4.76883185e-01, 1.53788412e-04,
       9.15879079e-01, 8.64908414e-02, 4.79528887e-01, 9.35681383e-01,
       9.77892918e-01, 5.85645655e-01, 1.57842356e-02, 7.62135212e-02,
       1.34855065e-02, 5.30445112e-02, 8.06446503e-01, 4.80600460e-03,
       5.04847224e-01, 8.68420588e-01, 8.92652368e-03, 5.92487141e-01,
      

In [59]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [60]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8466666666666667
[[118  17]
 [ 29 136]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



`Hyper Parameter`

In [61]:
model = LogisticRegression()
penalty = ['ll','l2','elasticnet']
c_val = [100,10,1.0,0.01]
solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag','saga']

In [62]:
params = dict(penalty = penalty,C= c_val,solver = solver)

In [63]:
### grid search cv

In [74]:
from sklearn.model_selection import StratifiedGroupKFold
cv = StratifiedGroupKFold(n_splits=5)

In [65]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [76]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits=5)

from sklearn.model_selection import GridSearchCV
params = dict(penalty=['l1', 'l2', 'elasticnet', 'none'], C=[100, 10, 1.0, 0.01], solver=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
grid = GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)
grid.fit(x_train, y_train)

d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
320 fits failed out of a total of 480.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [72]:
x_train

array([[ 0.04446722,  0.91377162, -0.14972402, ...,  0.57407122,
        -0.66673831,  1.58983898],
       [ 0.41722807, -0.74594213,  0.6030946 , ..., -0.61453878,
         0.30463008,  0.75341946],
       [ 0.83868939,  0.86018264,  0.66388059, ...,  0.72508104,
        -1.17953018, -1.15545179],
       ...,
       [ 0.04091467,  0.42796263, -0.00235298, ..., -1.92277177,
        -0.17104772,  1.63925652],
       [ 0.3393792 , -0.64015446,  0.25253995, ..., -1.39922826,
        -0.52991248, -0.7348109 ],
       [ 1.84815207, -0.31305803,  1.78069642, ...,  0.60451533,
        -1.56102804, -1.25040773]], shape=(700, 10))

In [77]:
grid.fit(x_train,y_train)

d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
320 fits failed out of a total of 480.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
 

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='accuracy')

In [78]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}

In [79]:
grid.best_score_

np.float64(0.8785714285714287)

In [80]:
y_pred = grid.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8533333333333334
[[124  11]
 [ 33 132]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



`Randomize CV`

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
Random = RandomizedSearchCV(model,param_distributions=params,scoring='accuracy',cv=5,n_jobs=-1)

In [126]:
Random.fit(x_train,y_train)

d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
36 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
6 fits failed with the following error:
Traceback (most recent call last):
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  Fi

RandomizedSearchCV(cv=6, estimator=LogisticRegression(), n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [127]:
Random.best_score_

np.float64(0.8714019058846644)

In [128]:
Random.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 0.01}

In [129]:
y_pred = Random.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8533333333333334
[[124  11]
 [ 33 132]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



`One Vs Rest`

In [130]:
from sklearn.datasets import make_classification
x,y = make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=15)

In [134]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=42)

In [135]:
model_multi = LogisticRegression(multi_class='ovr')
model_multi.fit(x_train,y_train)

d:\MachineLearning\venv\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [136]:
y_pred = model_multi.predict(x_test)

In [137]:
accuracy_score(y_test,y_pred)

0.79

In [138]:
randomCv = RandomizedSearchCV(estimator=model_multi,param_distributions=params,cv = 5,n_jobs=-1)

In [139]:
randomCv

RandomizedSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
                   n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']})

In [143]:
randomCv.fit(x_train,y_train)

d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\MachineLearning\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  Fi

RandomizedSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
                   n_jobs=-1,
                   param_distributions={'C': [100, 10, 1.0, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga']})

In [145]:
randomCv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 100}