#### numpy

In [10]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
arr2 = arr1.reshape(5,1) # 1 row ans and 5 col
print(arr2)
print(arr2.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((6,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### identity matrix and dia matrix

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

arr.dtype
arr.ndim

#### vectorized operation

In [17]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,20,30,40,50,60])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[11 22 33 44 55 66]
[ -9 -18 -27 -36 -45 -54]
[ 10  40  90 160 250 360]


#### universal function (to entire array)

In [23]:
arr = np.array([1,2,3,4,5,6])
np.sqrt(arr)
np.log(arr)
np.sin(arr)
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

### array slicing

In [25]:
arr = np.arange(0,15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [37]:
arr[1][2]

np.int64(7)

## Normalization formula

In [40]:
data = np.array([1,2,3,5,9,7]);
mean = np.mean(data);
std = np.std(data)
normalized_data = (data-mean)/std;
print(normalized_data);

[-1.24393264 -0.88852332 -0.53311399  0.17770466  1.59934197  0.88852332]


In [43]:
# logic operation
data = np.array([1,2,3,51,545,5,154,1,21,5,485,4,15,48,481,51,84,81,54,84])
data[data>5]

array([ 51, 545, 154,  21, 485,  15,  48, 481,  51,  84,  81,  54,  84])